import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="corporate">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Buat Header  */}
        <header>
          <Image src={"/images/logo.png"} width={320} height={60} alt="Logo UTI"></Image>
        </header>

        {/* Buat Content  */}
        <main>
        {children}
        </main>

        {/* Buat footer */}
        <footer className="text-center">
          Copyright &copy; 2025 - IF 22 B
        </footer>

      </body>
    </html>
  );
}
